### ISSUE TITLE
Consider line break change

### ISSUE THREAD

**Issue by JesperTreetop** [antirez/RESP3#12]
Since RESP3 is going to be backwards incompatible, wouldn't this be a good time to switch from `<CR><LF>` to just `<LF>`? In the service of making it an even more compact protocol, it would still be basically as readable. Maybe there's a very good reason to use `<CR><LF>` in RESP in general that I'm not aware of though.

**Comment by JesperTreetop** [comment]
Reading up a bit more, I see that this was the intention in 1.0 but that it was reverted in 1.1. Looking at the 1.0 gist and the 1.1 commit, I don't see the reason for this documented.

**Comment by antirez** [comment]
@JesperTreetop Hello, yes the original specification tried to simplify the newline separator, however after a closer look after all I think that the overhead win is not as good as the danger of client implementations supporting both protocols doing crazy things to shift between expecting one or two bytes... For instance even a RESP3 client now should start sending `HELLO` with `\r\n` and then continue in the other way. It's not rocket science, but given that the protocol switch will cause anyway a bit of confusion, I want to avoid that. Consider that instead, retaining the same separator, new clients willing to support RESP3 will just have to augment the parsing code with the new types, and all the other types will remain compatible without any change.

**Comment by JesperTreetop** [comment]
That makes sense and ease of client implementation is important, especially when there's a protocol upgrade now. It's good to have the reason documented.

**Comment by antirez** [comment]
Thanks @JesperTreetop, I added a FAQ section with this info.
